### ISSUE TITLE
Homework #4 Checklist

### ISSUE THREAD

**Issue by wdibi** [wdibi/Pivot#51]
- [x] Project clones and runs without crashing
- [x] All tests pass
- [x] Your compiler has commandline operations that can run the parser, the analyzer, and the generator separately
- [x] Can analyze and generate code for Hello World
- [x] Can analyze and generate code for a medium size program
- [x] Can detect lots of errors correctly
- [x] Your language has some “difficult” (or at least highly non-trivial) features to analyze
- [x] Code is nice, clean, and professional
- [x] Unit tests cover all interesting language features that should pass
- [x] Unit Tests for semantics - at least a dozen, preferably 30 or more, erroneous cases are covered
- [x] Code generator is complete for your language
- [x] Your language has a feature for which code generation was interesting and non-trivial
- [x] Code generator code is relatively efficient (no glaring problems)
- [x] Unit Tests for code generator - at least one
- [x] Unit Tests for code generator - at least several
- [x] Unit Tests for code generator - decent coverage
- [x] README page and companion website are complete, useful, and accurate
- [x] README page OR companion website has a link to the grammar (making it easy to lookup)
- [x] Project commit log shows that you've been working all semester
