### ISSUE TITLE
Homework 5 Checklist

### ISSUE THREAD

**Issue by JigarSwam** [wdibi/Pivot#63]
- [x] Project Can be Cloned
- [x] All Tests Pass
- [x] Can be run on commandline **without** -o and produces unoptimized code
- [x] Can be run on commandline **with** -o and produces optimized code
- [x] Repo contains several example programs of different complexities, that can be compiled
- [x] I can run the linter from the commandline using npm run lint and there are NO errors
- [x] 100% Test Coverage
- [x] New Strength Reduction Optimizations
- [x] TWO Non-trivial optimization that was not in Tiger
- [x] You have documented your optimizations

Total Points: 87 (137 Points Total, 50 from Lightning Talk)

**Comment by wdibi** [comment]
Add comments to readme

**Comment by wdibi** [comment]
Add comments to generator

**Comment by wdibi** [comment]
Add builtins to generator
